import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Auto-generated from category metadata in the docs pages.
  mainSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
